spring.profiles.active: develop
server:
  port: 8090
---
spring.config.activate.on-profile: develop
spring:
  datasource:
    url: jdbc:q:localhost:7001
    driver-class-name: jdbc
---
spring.config.activate.on-profile: test
spring:
  datasource:
    url: jdbc:q:localhost:7001
    driver-class-name: jdbc